apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  selector:
    app: {{ .Values.app }}
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: {{ .Values.application_port }}
      targetPort: {{ .Values.application_port }}
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: {{ .Values.nodeport }}

